name: bank_loan_app
description: A Flutter application for bank loan service.
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
